apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31317
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-python

