apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nodeapp
        image: jp.icr.io/oc-expo/nice-node:v1