apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31316
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-dotnet
